/// プレースホルダー画像の定数クラス
class PlaceholderImages {
  PlaceholderImages._();

  // 基本パス
  static const String facesPath = 'assets/images/';

  // ポジティブな画像（笑顔、健康、野菜）
  static const List<String> positiveImages = [
    'smile/01.jpg',
    'smile/02.jpg',
    'smile/03.jpg',
    'smile/04.jpg',
    'smile/05.jpg',
    'smile/06.jpg',
    'smile/07.jpg',
    'smile/08.jpg',
    'smile/09.jpg',
    'smile/10.jpg',
    'smile/11.jpg',
    'smile/12.jpg',
    'smile/13.jpg',
    'smile/14.jpg',
    'smile/15.jpg',
    'health/01.jpg',
    'health/02.jpg',
    'health/03.jpg',
    'health/04.jpg',
    'health/05.jpg',
    'health/06.jpg',
    'health/07.jpg',
    'health/08.jpg',
    'vegetables/01.jpg',
    'vegetables/02.jpg',
    'vegetables/03.jpg',
    'vegetables/04.jpg',
    'vegetables/05.jpg',
    'vegetables/06.jpg',
    'vegetables/07.jpg',
    'vegetables/08.jpg',
  ];

  // ネガティブな画像（悲しい、不健康な食べ物、悪い）
  static const List<String> negativeImages = [
    'sad/01.jpg',
    'sad/02.jpg',
    'sad/03.jpg',
    'sad/04.jpg',
    'sad/05.jpg',
    'sad/06.jpg',
    'sad/07.jpg',
    'sad/08.jpg',
    'sad/09.jpg',
    'sad/10.jpg',
    'sad/11.jpg',
    'sad/12.jpg',
    'sad/13.jpg',
    'sad/14.jpg',
    'sad/15.jpg',
    'sad/16.jpg',
    'sad/17.jpg',
    'sad/18.jpg',
    'sad/19.jpg',
    'sad/20.jpg',
    'sad/21.jpg',
    'sad/22.jpg',
    'sad/23.jpg',
    'sad/24.jpg',
    'sad/25.jpg',
    'sad/26.jpg',
    'sad/27.jpg',
    'sad/28.jpg',
    'sad/29.jpg',
    'badfood/01.jpg',
    'badfood/02.jpg',
    'badfood/03.jpg',
    'badfood/04.jpg',
    'badfood/05.jpg',
    'badfood/06.jpg',
    'badfood/07.jpg',
    'badfood/08.jpg',
    'badfood/09.jpg',
    'badfood/10.jpg',
    'badfood/11.jpg',
    'badfood/12.jpg',
    'badfood/13.jpg',
    'bad/01.jpg',
    'bad/02.jpg',
    'bad/03.jpg',
    'bad/04.jpg',
    'bad/05.jpg',
    'bad/06.jpg',
  ];
}