// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAkOuWB4ahTmjmOIRtazlVn3_dJm8jm2Y',
    appId: '1:1069601768015:web:6d635d7d6e2208ce16603a',
    messagingSenderId: '1069601768015',
    projectId: 'focusmint-analytics',
    authDomain: 'focusmint-analytics.firebaseapp.com',
    storageBucket: 'focusmint-analytics.firebasestorage.app',
    measurementId: 'G-ZYQYQD3N21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiw75PTLI2koWvFJAD1nBlie3liBaFulw',
    appId: '1:1069601768015:android:57f92c1da0866f9016603a',
    messagingSenderId: '1069601768015',
    projectId: 'focusmint-analytics',
    storageBucket: 'focusmint-analytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjT_i7Mr8IRqqJLUJzPYW9ac-agvSxLl8',
    appId: '1:1069601768015:ios:284cbe06f625e78216603a',
    messagingSenderId: '1069601768015',
    projectId: 'focusmint-analytics',
    storageBucket: 'focusmint-analytics.firebasestorage.app',
    iosBundleId: 'com.FocusMint.focusmint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjT_i7Mr8IRqqJLUJzPYW9ac-agvSxLl8',
    appId: '1:1069601768015:ios:284cbe06f625e78216603a',
    messagingSenderId: '1069601768015',
    projectId: 'focusmint-analytics',
    storageBucket: 'focusmint-analytics.firebasestorage.app',
    iosBundleId: 'com.FocusMint.focusmint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAkOuWB4ahTmjmOIRtazlVn3_dJm8jm2Y',
    appId: '1:1069601768015:web:570bd47fafa4748d16603a',
    messagingSenderId: '1069601768015',
    projectId: 'focusmint-analytics',
    authDomain: 'focusmint-analytics.firebaseapp.com',
    storageBucket: 'focusmint-analytics.firebasestorage.app',
    measurementId: 'G-XBY5B5DWNX',
  );

}